import { NextRequest } from 'next/server';
import { GoogleGenAI } from '@google/genai';

/**
 * Streaming Article Generation API
 * 
 * Uses Server-Sent Events (SSE) to stream article content
 * as it's being generated by the AI model.
 * 
 * V4: Real-time streaming with @google/genai SDK
 */

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface StreamRequest {
    keyword: string;
    context: string;
    modelId: string;
    apiKey: string;
}

export async function POST(request: NextRequest) {
    const body: StreamRequest = await request.json();
    const { keyword, context, modelId, apiKey } = body;

    // Validation - Hard Rule: No guessing or mock behavior
    if (!apiKey) {
        return new Response(
            JSON.stringify({ error: 'API key is required. Configure in Settings.' }),
            { status: 400, headers: { 'Content-Type': 'application/json' } }
        );
    }

    if (!modelId) {
        return new Response(
            JSON.stringify({ error: 'Model not selected. Select a model in Settings/AI Providers.' }),
            { status: 400, headers: { 'Content-Type': 'application/json' } }
        );
    }

    if (!keyword) {
        return new Response(
            JSON.stringify({ error: 'Keyword is required for article generation.' }),
            { status: 400, headers: { 'Content-Type': 'application/json' } }
        );
    }

    // Create readable stream for SSE
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
        async start(controller) {
            try {
                const ai = new GoogleGenAI({ apiKey });

                // Build the prompt
                const humanKeyword = keyword
                    .split('-')
                    .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
                    .join(' ');

                const today = new Date().toISOString().split('T')[0];

                const prompt = `Write a comprehensive, SEO-optimized article about "${humanKeyword}".

CONTEXT: ${context || 'General informational article'}

REQUIREMENTS:
1. Start with YAML frontmatter:
---
title: "${humanKeyword}"
date: "${today}"
description: "[Write 150-160 character meta description]"
author: "Editorial Team"
---

2. Write 2000+ words with:
   - Engaging introduction
   - Multiple H2 (##) and H3 (###) sections
   - Bullet points and numbered lists
   - Real product/tool recommendations (if applicable)
   - Statistics with sources
   - FAQ section with 5+ questions
   - Strong conclusion with call-to-action

3. Use markdown formatting:
   - **Bold** for important terms
   - Emoji sparingly (✅ ⚠️ 💡)
   - Tables for comparisons
   - Blockquotes for key insights

Start directly with --- (no preamble).`;

                // Stream the content using generateContentStream
                const response = await ai.models.generateContentStream({
                    model: modelId,
                    contents: prompt
                });

                // Send initial event
                controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: 'start', model: modelId })}\n\n`));

                // Stream chunks as they arrive
                for await (const chunk of response) {
                    const text = chunk.text;
                    if (text) {
                        controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: 'chunk', text })}\n\n`));
                    }
                }

                // Send completion event
                controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: 'done' })}\n\n`));
                controller.close();

            } catch (error) {
                const errorMessage = error instanceof Error ? error.message : 'Unknown error';
                controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: 'error', error: errorMessage })}\n\n`));
                controller.close();
            }
        }
    });

    return new Response(stream, {
        headers: {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
        },
    });
}
