import { getAllArticles } from '@/lib/content';
import Link from 'next/link';
import Dashboard from '@/components/Dashboard';

export default function Home() {
  const articles = getAllArticles();

  return (
    <main className="min-h-screen bg-neutral-50 px-4 py-8 md:px-8 lg:px-16 font-sans text-neutral-900 relative">
      <header className="mb-12 text-center">
        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight mb-4 bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600">
          The Future of Finance & Critical Tech
        </h1>
        <p className="text-xl text-neutral-600 max-w-2xl mx-auto mb-8">
          Autonomous insights generated by the Ifrit Engine.
        </p>

        {/* Dashboard Control (Client Component) */}
        <Dashboard />
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {articles.map((article) => (
          <Link href={`/${article.slug}`} key={article.slug} className="group block">
            <article className="h-full bg-white rounded-2xl shadow-sm border border-neutral-100 p-6 transition-all duration-300 hover:shadow-xl hover:-translate-y-1 overflow-hidden relative">
              <div className="absolute inset-0 bg-gradient-to-br from-transparent to-neutral-50 opacity-0 group-hover:opacity-100 transition-opacity" />
              <div className="relative z-10">
                <span className="inline-block px-3 py-1 mb-4 text-xs font-semibold tracking-wider text-blue-600 uppercase bg-blue-50 rounded-full">
                  Analysis
                </span>
                <h2 className="text-xl font-bold mb-3 group-hover:text-blue-600 transition-colors">
                  {article.title}
                </h2>
                <p className="text-neutral-600 line-clamp-3 mb-4 text-sm">
                  {article.description}
                </p>
                <div className="flex items-center justify-between text-xs text-neutral-400 mt-auto">
                  <span>{article.date}</span>
                  <span className="group-hover:translate-x-1 transition-transform">Read more &rarr;</span>
                </div>
              </div>
            </article>
          </Link>
        ))}
      </div>

      <footer className="mt-20 py-8 border-t border-neutral-200 text-center text-neutral-500 text-sm">
        &copy; 2025 AdSense Ifrit. All rights reserved.
      </footer>
    </main>
  );
}
