
import { CapabilityHandler, ExecuteOptions, ExecuteResult } from '../services/types';
import { AnalyzedKeyword } from '@/lib/keywords/types';

/**
 * Local Fallback Handler for Keyword Analysis
 * 
 * Provides simulated data when no AI keys are available.
 * Useful for development and demos.
 */
export const localKeywordAnalysisHandler: CapabilityHandler = {
    id: 'local-keyword-analyze',
    name: 'Local Simulation (Fallback)',
    source: 'local',
    capabilities: ['keyword-analyze'],
    priority: 10, // Low priority, only runs if others fail
    isAvailable: true,
    requiresApiKey: false,

    async execute(options: ExecuteOptions): Promise<ExecuteResult> {
        const startTime = Date.now();
        const { context, onProgress } = options;
        const keywords = (context?.keywords || []) as string[];

        if (!keywords.length) {
            return {
                success: false,
                error: 'No keywords provided for simulation',
                handlerUsed: 'local-keyword-analyze',
                source: 'local',
                latencyMs: 0
            };
        }

        // Simulate processing delay for realism
        const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

        onProgress?.({
            phase: 'starting',
            message: 'No AI keys found - Using simulation...'
        });

        // Split into steps
        await delay(500);

        onProgress?.({
            phase: 'handler',
            message: 'Generating simulated metrics...',
            current: 1,
            total: keywords.length
        });

        await delay(800);

        const results: AnalyzedKeyword[] = keywords.map(kw => ({
            keyword: kw,
            source: 'ai',
            niche: 'Simulated Niche',
            analysis: {
                keyword: kw,
                niche: 'Simulated Niche',
                estimatedCPC: '$' + (Math.random() * 15 + 0.5).toFixed(2),
                estimatedVolume: (Math.floor(Math.random() * 20000) + 100).toString(),
                competition: ['Low', 'Medium', 'High'][Math.floor(Math.random() * 3)],
                score: Math.floor(Math.random() * 100),
                intent: ['Commercial', 'Informational', 'Transactional'][Math.floor(Math.random() * 3)],
                reasoning: 'Generated by local simulation handler because no AI keys were configured.',
                relatedKeywords: [kw + ' review', 'best ' + kw, 'cheap ' + kw]
            }
        }));

        onProgress?.({
            phase: 'complete',
            message: `Simulated analysis for ${keywords.length} items.`
        });

        return {
            success: true,
            data: results,
            handlerUsed: 'local-keyword-analyze',
            source: 'local',
            latencyMs: Date.now() - startTime
        };
    }
};
