/**
 * ads.txt Generator
 * 
 * Generates the required ads.txt file for Google AdSense compliance.
 * This file must be placed at the root of the website (public/ads.txt)
 * for AdSense verification to work properly.
 * 
 * @see https://support.google.com/adsense/answer/12171612
 */

/**
 * Generate ads.txt content for Google AdSense
 * 
 * Format: google.com, pub-XXXXXXXXXXXXXXXX, DIRECT, f08c47fec0942fa0
 * - google.com: The ad network domain
 * - pub-XXXXXXXXXXXXXXXX: Your AdSense publisher ID
 * - DIRECT: Relationship type (you own the domain)
 * - f08c47fec0942fa0: Google's TAG ID (fixed value)
 * 
 * @param publisherId - The AdSense publisher ID (e.g., "ca-pub-1234567890123456")
 * @returns The ads.txt file content
 */
export function generateAdsTxt(publisherId: string): string {
    // Extract the pub ID if the full format was provided
    const pubId = publisherId.startsWith('ca-pub-')
        ? publisherId.replace('ca-pub-', 'pub-')
        : publisherId.startsWith('pub-')
            ? publisherId
            : `pub-${publisherId}`;

    return `# ads.txt file for Google AdSense
# Generated by Ifrit - AdSense Optimized Website Builder
# Last updated: ${new Date().toISOString().split('T')[0]}

# Google AdSense
google.com, ${pubId}, DIRECT, f08c47fec0942fa0

# Note: This file authorizes Google to serve ads on this domain.
# Do not modify the format above - it must match exactly for verification.
`;
}

/**
 * Generate robots.txt with sitemap reference
 * 
 * @param domain - The website domain
 * @returns robots.txt content
 */
export function generateRobotsTxt(domain: string): string {
    return `# robots.txt for ${domain}
# Generated by Ifrit

User-agent: *
Allow: /

# Sitemap location
Sitemap: https://${domain}/sitemap.xml

# Block admin/API paths (Next.js internal)
Disallow: /api/
Disallow: /_next/
`;
}

/**
 * Generate basic sitemap.xml
 * This is a template - actual articles should be added dynamically
 * 
 * @param domain - The website domain
 * @returns sitemap.xml content
 */
export function generateSitemapXml(domain: string): string {
    const today = new Date().toISOString().split('T')[0];

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://${domain}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://${domain}/about</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://${domain}/contact</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://${domain}/privacy</loc>
    <lastmod>${today}</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>https://${domain}/terms</loc>
    <lastmod>${today}</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
</urlset>
`;
}

/**
 * Generate web app manifest for PWA support
 * 
 * @param siteName - The website name
 * @param themeColor - Primary theme color
 * @param backgroundColor - Background color
 * @returns manifest.json content
 */
export function generateManifest(
    siteName: string,
    themeColor: string,
    backgroundColor: string = '#ffffff'
): string {
    return JSON.stringify({
        name: siteName,
        short_name: siteName.substring(0, 12),
        description: `${siteName} - Your trusted source for quality content`,
        start_url: '/',
        display: 'standalone',
        background_color: backgroundColor,
        theme_color: themeColor,
        icons: [
            {
                src: '/favicon.ico',
                sizes: '48x48',
                type: 'image/x-icon'
            },
            {
                src: '/icon-192.png',
                sizes: '192x192',
                type: 'image/png'
            },
            {
                src: '/icon-512.png',
                sizes: '512x512',
                type: 'image/png'
            }
        ]
    }, null, 2);
}
