/**
 * ads.txt Generator
 * FSD: lib/generators/adsTxtGenerator.ts
 * 
 * Generates ads.txt file content for Google AdSense compliance.
 * ads.txt must be placed at root of domain: example.com/ads.txt
 */

// ============================================================================
// Types
// ============================================================================

export interface AdsTxtLine {
    domain: string;
    publisherId: string;
    relationship: 'DIRECT' | 'RESELLER';
    tagId?: string;
}

export interface AdsTxtResult {
    content: string;
    lines: AdsTxtLine[];
    valid: boolean;
    errors?: string[];
}

// ============================================================================
// Generator Functions
// ============================================================================

/**
 * Generate ads.txt content for Google AdSense
 * @param publisherId - Google AdSense Publisher ID (format: pub-1234567890123456)
 * @returns Generated ads.txt content
 */
export function generateAdsTxt(publisherId: string): AdsTxtResult {
    const errors: string[] = [];

    // Validate publisher ID format
    if (!publisherId) {
        return {
            content: '',
            lines: [],
            valid: false,
            errors: ['Publisher ID is required'],
        };
    }

    // Check format: should be pub- followed by 16 digits
    const pubIdRegex = /^pub-\d{16}$/;
    if (!pubIdRegex.test(publisherId)) {
        errors.push(`Publisher ID format invalid. Expected: pub-XXXXXXXXXXXXXXXX (16 digits)`);
    }

    const lines: AdsTxtLine[] = [
        {
            domain: 'google.com',
            publisherId,
            relationship: 'DIRECT',
            tagId: 'f08c47fec0942fa0', // Google's tag ID for AdSense
        },
    ];

    // Generate the ads.txt content
    const content = [
        '# ads.txt - Authorized Digital Sellers',
        '# Generated by Ifrit for Google AdSense',
        `# Publisher ID: ${publisherId}`,
        `# Generated: ${new Date().toISOString().split('T')[0]}`,
        '',
        '# Google AdSense',
        `google.com, ${publisherId}, DIRECT, f08c47fec0942fa0`,
        '',
    ].join('\n');

    return {
        content,
        lines,
        valid: errors.length === 0,
        errors: errors.length > 0 ? errors : undefined,
    };
}

/**
 * Generate ads.txt with additional ad networks
 */
export function generateAdsTxtMultiNetwork(
    publisherId: string,
    additionalNetworks?: AdsTxtLine[]
): AdsTxtResult {
    const base = generateAdsTxt(publisherId);

    if (!base.valid || !additionalNetworks?.length) {
        return base;
    }

    const allLines = [...base.lines, ...additionalNetworks];

    const additionalContent = additionalNetworks
        .map(line => {
            const tagIdPart = line.tagId ? `, ${line.tagId}` : '';
            return `${line.domain}, ${line.publisherId}, ${line.relationship}${tagIdPart}`;
        })
        .join('\n');

    const content = base.content + additionalContent + '\n';

    return {
        content,
        lines: allLines,
        valid: true,
    };
}

/**
 * Validate existing ads.txt content
 */
export function validateAdsTxt(content: string): {
    valid: boolean;
    lines: number;
    hasGoogleAdsense: boolean;
    errors: string[];
} {
    const errors: string[] = [];
    const lines = content.split('\n').filter(line => {
        const trimmed = line.trim();
        return trimmed && !trimmed.startsWith('#');
    });

    let hasGoogleAdsense = false;

    for (const line of lines) {
        // Check for Google AdSense line
        if (line.toLowerCase().includes('google.com') && line.toLowerCase().includes('direct')) {
            hasGoogleAdsense = true;
        }

        // Validate line format (domain, pub-id, DIRECT/RESELLER, optional-tag)
        const parts = line.split(',').map(p => p.trim());
        if (parts.length < 3) {
            errors.push(`Invalid line: "${line}" - Expected format: domain, pub-id, DIRECT/RESELLER`);
        }
    }

    return {
        valid: errors.length === 0,
        lines: lines.length,
        hasGoogleAdsense,
        errors,
    };
}
